import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by the Workflow SDK on every build — gitignored, not ours to lint.
    "app/.well-known/workflow/**",
    // Unrelated sibling projects that happen to live on disk in this folder.
    "hengo/**",
    "money-flow/**",
  ]),
]);

export default eslintConfig;
